### ISSUE TITLE
Adicionar o resto dos membros do Grupo ao Repo 

### ISSUE THREAD

**Issue by MarkozAndre** [isel-leic-pdm/1516-1-LI51D#1]
Boas

Eu sou o único do meu grupo que estou no Repo e queria pedir que adicionasse os meus colegas. o Repo é o: 1516-1-LI51D-G12 e os users deles são: KamikazePT e Arma-Branca.
Ainda tentei adicionar eu mas não encontrei a opção, calculo que não tenha permissão para isso.

Cumprimentos

**Comment by palbp** [comment]
Já te dei permissões de Admin
